interface ImportMetaEnv {
	VITE_PUBLIC_FIREBASE_API_KEY: string;
	VITE_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
	VITE_PUBLIC_FIREBASE_PROJECT_ID: string;
	VITE_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
	VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
	VITE_PUBLIC_FIREBASE_APP_ID: string;
}
